from __future__ import annotations

import re

from app.normalize.amount import parse_decimal_amount
from app.normalize.date import normalize_transaction_date
from app.normalize.description import normalize_description
from app.parsers.base import BankName, PdfBankParser, StatementKind
from app.pipeline.models import Transaction

ROW_RE = re.compile(r"^\s*(\d{2}/\d{2}/\d{2})\s+(.*)$")

WITHDRAWAL_COL = 137
DEPOSIT_COL = 169
BALANCE_COL = 195

_PAGE_HEADER_PREFIXES = (
    "Page No",
    "Statement of account",
    "Account Branch",
    "Address",
    "PLOT",
    "NEAR",
    "MR     SAHIL",
    "City",
    "State",
    "E-16",
    "RATANLAL",
    "Phone no.",
    "OD Limit",
    "UDYOG",
    "Email",
    "KANPUR",
    "Cust ID",
    "UTTAR",
    "Account No",
    "A/C Open",
    "JOINT",
    "RTGS/NEFT",
    "Account Status",
    "Branch Code",
    "Account Type",
    "Nomination",
    "Statement From",
)

_PAGE_FOOTER_TOKENS = (
    "HDFC BANK LIMITED",
    "*Closing balance includes",
    "Contents of this statement",
    "GSTIN",
    "Registered Office Address",
    "computer generated statement",
    "not require signature",
)

_STOP_PREFIXES = (
    "STATEMENT SUMMARY",
    "Opening Balance",
    "Generated On",
    "Generated By",
)


class HdfcSavingsPdfParserV2(PdfBankParser):
    bank = BankName.HDFC
    statement_kind = StatementKind.SAVINGS

    def parse(self, extracted_text: str) -> list[Transaction]:
        lines = extracted_text.splitlines()
        self._find_header_line(lines)
        current: dict | None = None
        transactions: list[Transaction] = []

        for line in self._iter_table_lines(lines):
            date_match = ROW_RE.match(line)
            if date_match is not None:
                withdrawal_raw = line[WITHDRAWAL_COL:DEPOSIT_COL].strip()
                deposit_raw = line[DEPOSIT_COL:BALANCE_COL].strip()
                if withdrawal_raw or deposit_raw:
                    current = self._append_completed(transactions, current)
                    current = self._start_transaction(line, date_match)
                    continue

            self._append_continuation(current, transactions, line)

        if current is not None:
            transactions.append(self._build_transaction(current))

        return transactions

    @staticmethod
    def _find_header_line(lines: list[str]) -> str:
        for line in lines:
            if (
                "Date" in line
                and "Narration" in line
                and "Withdrawal Amt." in line
                and "Deposit Amt." in line
            ):
                return line
        raise ValueError("Could not locate the HDFC savings v2 transaction table")

    @staticmethod
    def _iter_table_lines(lines: list[str]):
        seen_header = False
        in_footer = False

        for line in lines:
            if "\x0c" in line or "Page No" in line:
                in_footer = False

            stripped = line.strip()
            if not stripped:
                continue

            if not seen_header:
                if (
                    "Date" in line
                    and "Narration" in line
                    and "Withdrawal Amt." in line
                ):
                    seen_header = True
                continue

            if in_footer:
                continue

            if stripped.startswith(_PAGE_HEADER_PREFIXES):
                continue

            if any(t in stripped for t in _PAGE_FOOTER_TOKENS):
                in_footer = True
                continue

            if "Date" in line and "Narration" in line:
                continue

            if stripped.startswith(_STOP_PREFIXES):
                return

            yield line

    @staticmethod
    def _is_data_row(line: str) -> bool:
        if len(line) < BALANCE_COL:
            return False
        withdrawal_raw = line[WITHDRAWAL_COL:DEPOSIT_COL].strip()
        deposit_raw = line[DEPOSIT_COL:BALANCE_COL].strip()
        return bool(withdrawal_raw or deposit_raw)

    @staticmethod
    def _append_completed(
        transactions: list[Transaction],
        current: dict | None,
    ) -> dict | None:
        if current is not None:
            transactions.append(HdfcSavingsPdfParserV2._build_transaction(current))
        return None

    @staticmethod
    def _start_transaction(line: str, date_match: re.Match) -> dict:
        date_raw = date_match.group(1)
        date_normalized = HdfcSavingsPdfParserV2._normalize_year(date_raw)

        middle = line[date_match.end(1) : WITHDRAWAL_COL].strip()
        parts = re.split(r"\s{2,}", middle)
        narration = parts[0].strip() if parts else ""

        withdrawal_raw = line[WITHDRAWAL_COL:DEPOSIT_COL].strip()
        deposit_raw = line[DEPOSIT_COL:BALANCE_COL].strip()

        return {
            "date": date_normalized,
            "description_parts": [narration],
            "withdrawal": withdrawal_raw,
            "deposit": deposit_raw,
        }

    @staticmethod
    def _append_continuation(
        current: dict | None,
        transactions: list[Transaction],
        line: str,
    ) -> None:
        continuation = line.strip()
        if not continuation:
            return
        if current is not None:
            current["description_parts"].append(continuation)
        elif transactions:
            tx = transactions[-1]
            tx.description = f"{tx.description} {continuation}"

    @staticmethod
    def _build_transaction(raw: dict) -> Transaction:
        parts = raw["description_parts"]
        description = normalize_description(" ".join(p for p in parts if p and p != "-"))
        withdrawal = parse_decimal_amount(str(raw["withdrawal"])) or parse_decimal_amount("0")
        deposit = parse_decimal_amount(str(raw["deposit"])) or parse_decimal_amount("0")
        amount = deposit if deposit > 0 else -withdrawal

        return Transaction(
            transaction_date=normalize_transaction_date(str(raw["date"])),
            description=description,
            amount=amount,
        )

    @staticmethod
    def _normalize_year(dd_mm_yy: str) -> str:
        parts = dd_mm_yy.split("/")
        return f"{parts[0]}/{parts[1]}/20{parts[2]}"
